parameters:
    database_driver:   pdo_mysql
    database_host:     sql8.lh.pl
    database_port:     ~
    database_name:     mathplate_angaze
    database_user:     mathplate
    database_password: alamakota

    mailer_transport:  smtp
    mailer_host:       127.0.0.1
    mailer_user:       ~
    mailer_password:   ~

    locale:            en
    secret:            ThisTokenIsNotSoSecretChangeIt
